services:
  angular-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - APP_NAME=${APP_NAME:-WalactWeb}
        - IPTV_API_URL=${IPTV_API_URL}
    container_name: angular-prod
    ports:
      - "8080:8080"
    restart: unless-stopped


#  angular-dev:
#    build:
#      context: ..
#      dockerfile: docker/dockerfile-dev
#      args:
#        - API_URL=${API_URL:-https://walactv.walerike.com/apiwalactv}
#        - APP_NAME=${APP_NAME:-WalactWeb}
#    container_name: angular-dev
#    ports:
#      - "4200:4200"
#    restart: unless-stopped
#    networks:
#      - walactv-network

networks:
  dokploy-network:
    external: true
